CREATE TABLE grow_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    -- status varchar NOT NULL, 
    role TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);