CREATE TABLE goals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    tree_bet INTEGER NOT NULL,
    complete_by DATE NOT NULL,
    completed BOOLEAN,
    user_id INTEGER 
        REFERENCES grow_users(id) ON DELETE CASCADE NOT NULL,
    goal_type_id INTEGER 
        REFERENCES goal_types(id) ON DELETE CASCADE NOT NULL
);
